from djanko_lib import pyx, heading, paragraph, image, link
file = pyx()
file.title('DJanko Demo')
file.add(heading('DJanko Webpage'))
file.add(paragraph('This is a simple webpage generated using DJanko'))
file.add(paragraph('DJanko removes the need for learning HTML with Python'))
file.add(paragraph('example image:'))
file.add(image('/dango.png', alt=' example image'))
file.add(paragraph(link('/', 'example link')))
file.add(paragraph('example headings:'))
file.add(heading('Heading 1', level=1))
file.add(heading('Heading 2', level=2))
file.add(heading('Heading 3', level=3))
file.add(heading('Heading 4', level=4))
file.add(heading('Heading 5', level=5))
file.add(heading('Heading 6', level=6))

content = file.compile()