# This home page is currently filled with a demo, but you can customize this home page to your heart's content. The 'index.py' page will always be the default home page
from djanko_lib import pyx, heading, paragraph, image, link, style
file = pyx()
# You can add custom styles
file.add(style('picture', ['width: 500px', 'length: 500px']))
file.title('djanko demo')
file.add(heading('djanko webpage'))
file.add(paragraph('This is a simple webpage generated using djanko'))
file.add(paragraph('djanko removes the need for learning HTML with Python'))
file.add(paragraph('example image:'))
# You can add images: file.add(image('/dango.png', alt=' example image'))
file.add(heading("# You can add images: file.add(image('/dango.png', alt=' example image'))", level=6))
file.add(image('/dango.png', alt=' example image'))
# You can apply styles to any element, like an image: file.add(style('picture', ['width: 500px', 'length: 500px'])), then: file.add(image('/dango.png', alt=' example image', styles='picture'))
file.add(heading("# You can apply styles to any element, like an image: file.add(style('picture', ['width: 500px', 'length: 500px'])), then: file.add(image('/dango.png', alt=' example image', styles='picture'))", level=6))
file.add(image('/dango.png', alt=' example image', styles='picture'))
# You can embed links as paragraphs, and parents and children structure also works here: file.add(paragraph(link('/', 'example link')))
file.add(heading("# You can embed links as paragraphs, and parents and children structure also works here: file.add(paragraph(link('/', 'example link')))", level=6))
file.add(paragraph(link('/', 'example link')))
file.add(paragraph('example headings:'))
# Headings can have varing levels of size, ranging from 1, biggest, to 6, smallest: file.add(heading('Heading 1', level=1))
file.add(heading("# Headings can have varing levels of size, ranging from 1, biggest, to 6, smallest: file.add(heading('Heading 1', level=1))", level=6))
file.add(heading('Heading 1', level=1))
file.add(heading('Heading 2', level=2))
file.add(heading('Heading 3', level=3))
file.add(heading('Heading 4', level=4))
file.add(heading('Heading 5', level=5))
file.add(heading('Heading 6', level=6))
# You can also add custom HTML elements: file.add('<p>Custom Element</p>')
file.add(heading(r"# You can also add custom HTML elements:", level=6))
file.add('<p>Custom Element</p>')

content = file.compile()